name: dsai-m3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - jupyter
  - notebook
  - ipywidgets
  - pip:
      - textblob
      - transformers
      - torch
      - datasets
